java -jar target/additional-content-jar-files-1.0-SNAPSHOT.jar com.sid.tutorials.spring.boot3.java.app.App
jar -cvf additional-content-jar-files-1.0-SNAPSHOT.jar -C target/classes/ .
jar -tvf additional-content-jar-files-1.0-SNAPSHOT.jar
java -jar additional-content-jar-files-1.0-SNAPSHOT.jar
jar -xvf additional-content-jar-files-1.0-SNAPSHOT.jar
